"""
Sentinel Training Data Simulator
=================================
Generates 2M transactions across 3 institutions:
  - NeoBank (fiat-only)
  - CryptoEx (crypto-only)
  - FinBridge (hybrid)

Fraud patterns implemented:
  Fiat:   account_takeover | mule_network | synthetic_identity | bec
  Crypto: mixer_usage | rug_pull | phishing | pig_butchering
  Cross:  immediate_laundering | delayed_laundering | structuring_to_crypto | crypto_to_fiat

Fixes over v1:
  - Balance tracking (sender_balance_before/after, balance_drain_ratio)
  - Per-user velocity baselines + velocity_ratio / amount_ratio features
  - Canonical identity_hash across all modalities
  - fraud_network_id groups all txns in a mule ring
  - Archetype-specific log-normal amount distributions
  - receiver_hash on all fiat transactions
  - Device + IP hashes on both fiat and crypto
  - All 4 cross-modality laundering patterns
  - All 4 crypto fraud patterns
  - Micro-anomalies on legitimate users
  - Full schema alignment with Sentinel data model
"""

import hashlib
import uuid
import random
import json
import os
import yaml
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from scipy import stats
from faker import Faker
from tqdm import tqdm
from collections import defaultdict
from pathlib import Path

fake = Faker()
rng = np.random.default_rng(42)

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────

SHARED_SALT      = os.getenv("SENTINEL_SALT", "sentinel_consortium_2026_v1")
DEVICE_SALT      = os.getenv("DEVICE_SALT",   "sentinel_device_2026_v1")
IP_SALT          = os.getenv("IP_SALT",        "sentinel_ip_2026_v1")

START_TIME       = datetime(2026, 1, 1, 0, 0, 0)
SIM_DAYS         = 30
N_IDENTITIES     = 10_000    # Shared identity pool
TARGET_FIAT_TXN  = 1_500_000
TARGET_CRYPTO_TXN = 500_000

# Fraud rates per simulator
FIAT_FRAUD_RATE   = 0.020   # 2.0%
CRYPTO_FRAUD_RATE = 0.030   # 3.0%

# Cross-modality: % of fiat fraud that spawns a crypto leg
CROSS_MODAL_RATE  = 0.20    # 20% of fiat fraud → crypto bridge

# Path to calibration YAML generated by scripts/calibrate_paysim.py
CALIBRATION_PATH = os.getenv("CALIBRATION_PATH", "data/calibration/calibration.yaml")


# -----------------------------------------------------------------
# CALIBRATION LOADER
# Reads calibration.yaml and derives runtime constants.
# Falls back to safe hardcoded defaults if the file is missing.
# -----------------------------------------------------------------

def load_calibration(path):
    p = Path(path)
    if not p.exists():
        print(f"[calibration] WARNING: {path} not found -- using hardcoded defaults.")
        return {}
    with open(p) as f:
        cal = yaml.safe_load(f)
    print(f"[calibration] Loaded from {path}")
    return cal or {}


def _build_archetype_lognorm(cal):
    """Compute (mu, sigma) for each fiat archetype from paysim_fit + offsets."""
    fit      = cal.get("paysim_fit", {})
    base_mu  = fit.get("mu",    12.97)
    base_sg  = fit.get("sigma",  1.30)
    arch_cfg = cal.get("archetype_amount_lognorm", {})
    defaults = {
        "salary_worker":  {"mu_offset": -4.7, "sigma_scale": 0.70},
        "freelancer":     {"mu_offset": -4.2, "sigma_scale": 1.00},
        "small_business": {"mu_offset": -3.2, "sigma_scale": 1.20},
        "retiree":        {"mu_offset": -5.5, "sigma_scale": 0.50},
        "student":        {"mu_offset": -6.0, "sigma_scale": 0.60},
    }
    result = {}
    for arch, fallback in defaults.items():
        cfg   = arch_cfg.get(arch, fallback)
        mu    = base_mu + cfg.get("mu_offset",   fallback["mu_offset"])
        sigma = base_sg * cfg.get("sigma_scale", fallback["sigma_scale"])
        result[arch] = (round(mu, 4), round(sigma, 4))
        print(f"[calibration]   {arch:<20} mu={mu:.2f}, sigma={sigma:.2f}"
              f"  -> median ~${int(round(2.718**mu)):,}")
    return result


def _build_fraud_params(cal):
    """Extract ATO fraud params. Applies lower bounds so PaySim degenerate values do not break the simulator."""
    raw_burst = cal.get("fraud_burst_count", [3, 5])
    burst_min = max(3, raw_burst[0])
    burst_max = max(5, raw_burst[1])
    drain_min = min(0.80, float(cal.get("fraud_drain_ratio_min",    0.80)))
    drain_max = min(0.99, float(cal.get("fraud_drain_ratio_median", 0.97)))
    return {
        "burst_count":       (burst_min, burst_max),
        "drain_min":         drain_min,
        "drain_max":         drain_max,
        "amount_multiplier": max(1.0, cal.get("fraud_amount_multiplier", 3.0)),
    }


def _build_fraud_hour_weights(cal):
    """Blend 60% domain-knowledge (02-05 AM spike) + 40% PaySim calibrated weights."""
    domain = [
        0.15, 0.15, 0.20, 0.20, 0.15, 0.15,
        0.05, 0.03, 0.03, 0.03, 0.03, 0.03,
        0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
        0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
    ]
    paysim = cal.get("fraud_hour_weights", domain)
    if len(paysim) != 24:
        print("[calibration] WARNING: fraud_hour_weights wrong length, using domain defaults")
        paysim = domain
    blended = [0.60 * d + 0.40 * p for d, p in zip(domain, paysim)]
    total   = sum(blended)
    return [w / total for w in blended]


# Load calibration once at import time
print("[calibration] Loading...")
_CAL                = load_calibration(CALIBRATION_PATH)
_ARCHETYPE_LOGNORM  = _build_archetype_lognorm(_CAL)
_FRAUD_PARAMS       = _build_fraud_params(_CAL)
_FRAUD_HOUR_WEIGHTS = _build_fraud_hour_weights(_CAL)
print(f"[calibration] Fraud burst count: {_FRAUD_PARAMS['burst_count']}")
print(f"[calibration] Fraud drain range: [{_FRAUD_PARAMS['drain_min']:.2f}, {_FRAUD_PARAMS['drain_max']:.2f}]")
print("[calibration] Ready.\n")

# Known mixer addresses (Ethereum)
MIXER_ADDRESSES = [
    "0x47CE0C6eD5B0Ce3d3A51fdb1C52DC66a7c3c2936",  # Tornado Cash
    "0x8d12A197cB00D4747a1fe03395095ce2A5CC6819",  # EtherDelta (known risk)
    "0xA160cdAB225685dA1d56aa342Ad8841c3b53f291",  # Blender.io
]

KNOWN_DeFi_PROTOCOLS = [
    "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",  # Uniswap V2 Router
    "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45",  # Uniswap V3 Router
    "0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9",  # Aave V2
]

# ─────────────────────────────────────────────
# ARCHETYPE DEFINITIONS
# Each archetype has: weight, txn_per_day (weekday), amount distribution params,
# income_range, counterparty_count_range
# Amount distribution: log-normal (mean_log, sigma_log) → calibrated to PaySim
# ─────────────────────────────────────────────

ARCHETYPES = {
    "salary_worker": {
        "weight":           0.40,
        "txn_per_day":      2.5,
        "amount_lognorm":   None,          # salary_worker: filled from calibration≈$1100 median
        "income_range":     (3000, 8000),
        "counterparties":   (5, 15),
        "repeat_rate":      0.80,
        "kyc_status":       "verified",
    },
    "freelancer": {
        "weight":           0.25,
        "txn_per_day":      5.0,
        "amount_lognorm":   None,          # freelancer: filled from calibration≈$1800 median, high variance
        "income_range":     (2000, 15000),
        "counterparties":   (10, 30),
        "repeat_rate":      0.60,
        "kyc_status":       "verified",
    },
    "small_business": {
        "weight":           0.15,
        "txn_per_day":      12.0,
        "amount_lognorm":   None,          # small_business: filled from calibration≈$4900 median, very high variance
        "income_range":     (10000, 100000),
        "counterparties":   (20, 50),
        "repeat_rate":      0.50,
        "kyc_status":       "verified",
    },
    "retiree": {
        "weight":           0.10,
        "txn_per_day":      1.0,
        "amount_lognorm":   None,          # retiree: filled from calibration≈$490 median, low variance
        "income_range":     (1500, 4000),
        "counterparties":   (3, 8),
        "repeat_rate":      0.90,
        "kyc_status":       "verified",
    },
    "student": {
        "weight":           0.10,
        "txn_per_day":      1.5,
        "amount_lognorm":   None,          # student: filled from calibration≈$245 median
        "income_range":     (500, 2000),
        "counterparties":   (2, 6),
        "repeat_rate":      0.75,
        "kyc_status":       "pending",
    },
}
# Apply calibrated lognorm to every archetype
for _arch, _lognorm in _ARCHETYPE_LOGNORM.items():
    if _arch in ARCHETYPES:
        ARCHETYPES[_arch]["amount_lognorm"] = _lognorm

CRYPTO_ARCHETYPES = {
    "hodler":   {"weight": 0.30, "txn_per_day": 0.05,  "amount_range": (500,   5000)},
    "trader":   {"weight": 0.25, "txn_per_day": 1.5,   "amount_range": (1000,  20000)},
    "defi":     {"weight": 0.20, "txn_per_day": 0.5,   "amount_range": (500,   10000)},
    "merchant": {"weight": 0.15, "txn_per_day": 3.0,   "amount_range": (50,    5000)},
    "p2p":      {"weight": 0.10, "txn_per_day": 0.4,   "amount_range": (20,    500)},
}

# Hourly transaction weight (index = hour 0-23)
HOURLY_WEIGHTS = [
    0.05, 0.03, 0.03, 0.03, 0.04, 0.06,   # 00-05
    0.10, 0.20, 0.40, 0.60, 0.80, 0.90,   # 06-11
    0.85, 0.80, 0.90, 1.00, 0.90, 0.75,   # 12-17
    0.55, 0.40, 0.30, 0.20, 0.12, 0.07,   # 18-23
]
_hw_total = sum(HOURLY_WEIGHTS)
HOURLY_WEIGHTS = [w / _hw_total for w in HOURLY_WEIGHTS]


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def sha256(value: str) -> str:
    return hashlib.sha256(value.encode()).hexdigest()

def identity_hash(email: str) -> str:
    """Canonical cross-client identity key."""
    return sha256(f"{email}{SHARED_SALT}")

def device_hash(device_id: str) -> str:
    return sha256(f"{device_id}{DEVICE_SALT}")

def ip_hash(ip: str) -> str:
    return sha256(f"{ip}{IP_SALT}")

def sample_hour() -> int:
    return rng.choice(24, p=HOURLY_WEIGHTS)

def sample_fraud_hour() -> int:
    """
    Returns an hour index weighted by _FRAUD_HOUR_WEIGHTS.
    Blends 60% domain-knowledge off-hours spike + 40% PaySim calibration.
    """
    return int(rng.choice(24, p=_FRAUD_HOUR_WEIGHTS))

def rand_ts(day: int, hour_fn=sample_hour) -> datetime:
    return START_TIME + timedelta(
        days=day,
        hours=int(hour_fn()),
        minutes=random.randint(0, 59),
        seconds=random.randint(0, 59),
    )

def sample_amount(archetype: str) -> float:
    mu, sigma = ARCHETYPES[archetype]["amount_lognorm"]
    return max(10.0, float(rng.lognormal(mu, sigma)))

def txn_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:12]}"

def fake_wallet() -> str:
    return f"0x{uuid.uuid4().hex[:40]}"

def fake_tx_hash() -> str:
    return f"0x{uuid.uuid4().hex}{uuid.uuid4().hex[:24]}"


# ─────────────────────────────────────────────
# IDENTITY POOL
# ─────────────────────────────────────────────

def build_identity_pool(n: int) -> list[dict]:
    """
    Creates the shared identity layer used by all 3 simulators.
    Each identity has:
      - identity_hash: canonical cross-client key (SHA-256 of email+salt)
      - archetype, income, counterparties, balance, velocity_baseline
      - device_hash, ip_hash (for fraud signal)
      - crypto_wallet (some identities also have crypto presence)
    """
    arch_keys = list(ARCHETYPES.keys())
    arch_weights = [ARCHETYPES[a]["weight"] for a in arch_keys]

    identities = []
    print(f"Building {n:,} consortium identities...")
    for _ in tqdm(range(n)):
        email   = fake.email()
        arch    = random.choices(arch_keys, weights=arch_weights)[0]
        cfg     = ARCHETYPES[arch]
        income  = random.randint(*cfg["income_range"])
        n_counterparties = random.randint(*cfg["counterparties"])
        account_age = random.randint(30, 3650)

        # Per-user velocity baseline (txns/day over simulated period)
        # Used later to compute velocity_ratio feature
        velocity_baseline = cfg["txn_per_day"] * random.uniform(0.7, 1.3)

        # Running balance: start with 1–6 months of income
        starting_balance = income * random.uniform(1.0, 6.0)

        # Assign each user a stable device and IP (attackers will override these)
        user_device = fake.uuid4()
        user_ip     = fake.ipv4()

        identities.append({
            "identity_hash":      identity_hash(email),
            "email":              email,           # retained for hash verification; never exported
            "archetype":          arch,
            "income_monthly":     income,
            "account_age_days":   account_age,
            "kyc_status":         cfg["kyc_status"],
            "velocity_baseline":  velocity_baseline,
            "balance":            starting_balance,
            "counterparties":     [identity_hash(fake.email()) for _ in range(n_counterparties)],
            "device_hash":        device_hash(user_device),
            "ip_hash":            ip_hash(user_ip),
            "has_crypto":         random.random() < 0.35,   # 35% also use crypto
            "crypto_wallet":      fake_wallet(),
            "crypto_archetype":   random.choices(
                list(CRYPTO_ARCHETYPES.keys()),
                weights=[v["weight"] for v in CRYPTO_ARCHETYPES.values()]
            )[0],
            # Velocity tracking (populated during simulation)
            "_txn_count_30d":     0,
            "_amount_sum_30d":    0.0,
            "_txn_history":       [],   # [(timestamp, amount)] for window features
        })

    return identities


# ─────────────────────────────────────────────
# FEATURE HELPERS (computed at generation time)
# ─────────────────────────────────────────────

def compute_velocity_features(user: dict, current_ts: datetime, window_hours: list[int]) -> dict:
    """
    Compute count and sum features over multiple time windows.
    Uses _txn_history which stores (ts, amount) tuples.
    """
    feats = {}
    history = user["_txn_history"]
    for h in window_hours:
        cutoff = current_ts - timedelta(hours=h)
        window_txns = [(ts, amt) for ts, amt in history if ts >= cutoff]
        feats[f"count_{h}h"]      = len(window_txns)
        feats[f"sum_amount_{h}h"] = round(sum(amt for _, amt in window_txns), 2)
    return feats

def update_user_history(user: dict, ts: datetime, amount: float):
    """Append to rolling history, prune >7 days old."""
    user["_txn_history"].append((ts, amount))
    cutoff = ts - timedelta(days=7)
    user["_txn_history"] = [(t, a) for t, a in user["_txn_history"] if t >= cutoff]
    user["_txn_count_30d"]  += 1
    user["_amount_sum_30d"] += amount

def velocity_ratio(user: dict, count_24h: int) -> float:
    """How many times faster than the user's baseline is this 24h count?"""
    baseline_24h = user["velocity_baseline"]
    if baseline_24h == 0:
        return 0.0
    return round(count_24h / baseline_24h, 3)

def amount_ratio(user: dict, amount: float) -> float:
    """How many times the user's average transaction amount is this?"""
    if user["_txn_count_30d"] == 0:
        return 1.0
    avg = user["_amount_sum_30d"] / user["_txn_count_30d"]
    return round(amount / avg, 3) if avg > 0 else 1.0


# ─────────────────────────────────────────────
# FIAT TRANSACTION BUILDER
# ─────────────────────────────────────────────

def build_fiat_txn(
    sender: dict,
    receiver_hash: str,
    amount: float,
    ts: datetime,
    transfer_type: str = "ach",
    transfer_network: str = "domestic",
    is_fraud: bool = False,
    fraud_type: str = None,
    fraud_network_id: str = None,
    cross_modality_fraud_id: str = None,
    override_device_hash: str = None,
    override_ip_hash: str = None,
) -> dict:
    """Builds a fully-featured fiat transaction record."""

    balance_before = max(0.0, sender["balance"])
    balance_after  = max(0.0, balance_before - amount)
    drain_ratio    = round(amount / balance_before, 4) if balance_before > 0 else 0.0

    vel_feats = compute_velocity_features(sender, ts, [1, 6, 24, 168])
    v_ratio   = velocity_ratio(sender, vel_feats["count_24h"])
    a_ratio   = amount_ratio(sender, amount)

    # Deduct balance (legitimate drain tracked per user)
    sender["balance"] = balance_after

    is_first_time = receiver_hash not in sender["counterparties"]
    if not is_first_time:
        sender["counterparties"].append(receiver_hash)

    update_user_history(sender, ts, amount)

    return {
        # ── Identifiers ──────────────────────────────────
        "transaction_id":             txn_id("neobank"),
        "client_id":                  "neobank_prod",
        "timestamp":                  ts.isoformat() + "Z",
        "modality":                   "fiat",

        # ── Canonical cross-client key ───────────────────
        "identity_hash":              sender["identity_hash"],

        # ── Hashed participants ──────────────────────────
        "sender_hash":                sender["identity_hash"],
        "receiver_hash":              receiver_hash,
        "sender_device_hash":         override_device_hash or sender["device_hash"],
        "sender_ip_hash":             override_ip_hash     or sender["ip_hash"],

        # ── Transfer details ─────────────────────────────
        "amount_usd":                 round(amount, 2),
        "transfer_type":              transfer_type,
        "transfer_network":           transfer_network,

        # ── Account features ─────────────────────────────
        "sender_account_age_days":    sender["account_age_days"],
        "sender_kyc_status":          sender["kyc_status"],
        "sender_archetype":           sender["archetype"],
        "is_first_time_receiver":     is_first_time,

        # ── Balance features (Gap 2 fix) ─────────────────
        "sender_balance_before":      round(balance_before, 2),
        "sender_balance_after":       round(balance_after, 2),
        "balance_drain_ratio":        drain_ratio,

        # ── Velocity features (Gap 3 fix) ────────────────
        "count_1h":                   vel_feats["count_1h"],
        "count_6h":                   vel_feats["count_6h"],
        "count_24h":                  vel_feats["count_24h"],
        "count_7d":                   vel_feats["count_168h"],
        "sum_amount_1h":              vel_feats["sum_amount_1h"],
        "sum_amount_24h":             vel_feats["sum_amount_24h"],
        "sum_amount_7d":              vel_feats["sum_amount_168h"],
        "velocity_ratio":             v_ratio,
        "amount_ratio":               a_ratio,
        "velocity_baseline_daily":    round(sender["velocity_baseline"], 3),

        # ── Temporal features ────────────────────────────
        "hour_of_day":                ts.hour,
        "day_of_week":                ts.weekday(),
        "is_weekend":                 ts.weekday() >= 5,
        "is_unusual_hour":            ts.hour < 6 or ts.hour >= 23,

        # ── Ground truth ─────────────────────────────────
        "is_fraud":                   is_fraud,
        "fraud_type":                 fraud_type,
        "fraud_network_id":           fraud_network_id,
        "cross_modality_fraud_id":    cross_modality_fraud_id,
    }


# ─────────────────────────────────────────────
# CRYPTO TRANSACTION BUILDER
# ─────────────────────────────────────────────

def build_crypto_txn(
    user: dict,
    sender_wallet_hash: str,
    receiver_wallet_hash: str,
    amount_usd: float,
    ts: datetime,
    transfer_type: str = "withdrawal",
    receiver_wallet_type: str = "user_wallet",
    known_mixer_interaction: bool = False,
    receiver_wallet_age_days: int = None,
    is_fraud: bool = False,
    fraud_type: str = None,
    fraud_network_id: str = None,
    cross_modality_fraud_id: str = None,
    override_device_hash: str = None,
    override_ip_hash: str = None,
) -> dict:
    """Builds a fully-featured crypto transaction record."""

    crypto_arch = CRYPTO_ARCHETYPES.get(user.get("crypto_archetype", "hodler"), {})
    cryptocurrency = random.choices(
        ["ETH", "BTC", "USDT", "USDC", "SOL"],
        weights=[0.40, 0.25, 0.20, 0.10, 0.05]
    )[0]
    eth_price = 2800.0  # fixed for simulation
    amount_crypto = round(amount_usd / eth_price, 6)

    return {
        # ── Identifiers ──────────────────────────────────
        "transaction_id":                 txn_id("cryptoex"),
        "client_id":                      "cryptoex_prod",
        "timestamp":                      ts.isoformat() + "Z",
        "modality":                       "crypto",

        # ── Canonical cross-client key (Gap 4 fix) ───────
        "identity_hash":                  user["identity_hash"],

        # ── Hashed participants ──────────────────────────
        "sender_wallet_hash":             sender_wallet_hash,
        "receiver_wallet_hash":           receiver_wallet_hash,
        "user_email_hash":                user["identity_hash"],
        "sender_device_hash":             override_device_hash or user["device_hash"],
        "sender_ip_hash":                 override_ip_hash     or user["ip_hash"],

        # ── Crypto details ───────────────────────────────
        "amount_usd":                     round(amount_usd, 2),
        "amount_crypto":                  amount_crypto,
        "cryptocurrency":                 cryptocurrency,
        "blockchain":                     "ethereum",
        "transaction_hash":               fake_tx_hash(),
        "gas_price_gwei":                 random.randint(10, 150),
        "block_number":                   random.randint(19_000_000, 21_000_000),
        "confirmations":                  random.randint(1, 50),

        # ── Wallet features ──────────────────────────────
        "sender_wallet_age_days":         user.get("account_age_days", 30),
        "sender_lifetime_txn_count":      user.get("_txn_count_30d", 0),
        "sender_lifetime_volume_usd":     round(user.get("_amount_sum_30d", 0), 2),
        "receiver_wallet_type":           receiver_wallet_type,
        "receiver_wallet_age_days":       receiver_wallet_age_days if receiver_wallet_age_days is not None else random.randint(30, 1000),

        # ── Risk indicators ──────────────────────────────
        "known_mixer_interaction":        known_mixer_interaction,
        "is_first_time_receiver":         random.random() < 0.3,
        "immediate_withdrawal":           False,

        # ── Temporal ─────────────────────────────────────
        "hour_of_day":                    ts.hour,
        "day_of_week":                    ts.weekday(),
        "is_unusual_hour":                ts.hour < 6,

        # ── Ground truth ─────────────────────────────────
        "is_fraud":                       is_fraud,
        "fraud_type":                     fraud_type,
        "fraud_network_id":               fraud_network_id,
        "cross_modality_fraud_id":        cross_modality_fraud_id,
    }


# ─────────────────────────────────────────────
# NEOBANK SIMULATOR  (fiat-only)
# ─────────────────────────────────────────────

class NeoBankSimulator:
    def __init__(self, identities: list[dict]):
        self.identities = identities
        self.transactions: list[dict] = []
        self.cross_modal_bridges: list[dict] = []   # fiat→crypto links

    # ── Normal transaction ────────────────────────────

    def _normal_txn(self, user: dict, day: int) -> dict:
        amount = sample_amount(user["archetype"])
        repeat = random.random() < ARCHETYPES[user["archetype"]]["repeat_rate"]
        if repeat and user["counterparties"]:
            receiver = random.choice(user["counterparties"])
        else:
            receiver = identity_hash(fake.email())

        transfer_type = random.choices(
            ["ach", "wire", "p2p", "rtp"],
            weights=[0.60, 0.20, 0.15, 0.05]
        )[0]
        transfer_network = random.choices(
            ["same_bank", "domestic", "international"],
            weights=[0.40, 0.50, 0.10]
        )[0]

        ts = rand_ts(day)
        return build_fiat_txn(user, receiver, amount, ts,
                              transfer_type=transfer_type,
                              transfer_network=transfer_network)

    # ── Micro-anomalies (legitimate edge cases) ───────

    def _micro_anomaly(self, user: dict, day: int) -> dict:
        """Occasional large-but-legitimate transfers: travel wire, inheritance, etc."""
        anomaly = random.choices(
            ["travel_wire", "large_one_time", "income_spike"],
            weights=[0.50, 0.30, 0.20]
        )[0]

        if anomaly == "travel_wire":
            amount = random.uniform(1000, 8000)
            transfer_type = "wire"
            transfer_network = "international"
        elif anomaly == "large_one_time":
            amount = random.uniform(10000, 50000)
            transfer_type = "wire"
            transfer_network = "domestic"
        else:  # income_spike
            amount = user["income_monthly"] * random.uniform(1.5, 3.0)
            transfer_type = "ach"
            transfer_network = "domestic"

        receiver = identity_hash(fake.email())
        ts = rand_ts(day)
        txn = build_fiat_txn(user, receiver, amount, ts,
                              transfer_type=transfer_type,
                              transfer_network=transfer_network)
        return txn

    # ── Fraud Pattern 1: Account Takeover ────────────

    def _inject_ato(self, victim: dict, day: int) -> list[dict]:
        """
        Attacker steals credentials, initiates rapid burst of large transfers
        at 2–4 AM using a new device/IP.
        """
        attacker_device = device_hash(fake.uuid4())
        attacker_ip     = ip_hash(fake.ipv4_private())
        base_ts         = rand_ts(day, hour_fn=sample_fraud_hour)

        txns = []
        # Use calibrated burst count and drain ratio from calibration.yaml
        burst_min, burst_max = _FRAUD_PARAMS["burst_count"]
        n_transfers = random.randint(burst_min, burst_max)
        for i in range(n_transfers):
            drain_pct = random.uniform(_FRAUD_PARAMS["drain_min"],
                                       _FRAUD_PARAMS["drain_max"])
            amount    = max(100.0, victim["balance"] * drain_pct / n_transfers)
            ts        = base_ts + timedelta(minutes=i * random.randint(1, 4))
            receiver  = identity_hash(fake.email())  # mule: never seen before

            txn = build_fiat_txn(
                victim, receiver, amount, ts,
                transfer_type="wire",
                transfer_network="international",
                is_fraud=True,
                fraud_type="account_takeover",
                override_device_hash=attacker_device,
                override_ip_hash=attacker_ip,
            )
            txns.append(txn)

        return txns

    # ── Fraud Pattern 2: Mule Network ────────────────

    def _inject_mule_network(self, identities_pool: list[dict], day: int) -> list[dict]:
        """
        Star topology: stolen funds fan out to 5–10 mule accounts,
        which then aggregate into a single account (optional crypto cashout).
        """
        network_id = f"mule_{uuid.uuid4().hex[:8]}"
        n_mules    = random.randint(5, 10)
        mules      = random.sample(identities_pool, min(n_mules, len(identities_pool)))

        # Give mules low account age to mimic real recruitment pattern
        for m in mules:
            m["account_age_days"] = random.randint(1, 30)
            m["balance"] = 0.0

        # Aggregator = one of the mules, or create fresh
        aggregator = random.choice(mules)
        base_ts    = rand_ts(day, hour_fn=sample_fraud_hour)

        txns = []
        total_aggregated = 0.0

        # Stage 1: Fraud source → each mule
        fraud_source = random.choice(identities_pool)
        for i, mule in enumerate(mules):
            amount = random.uniform(2000, 10000)
            ts     = base_ts + timedelta(minutes=i * random.randint(3, 8))
            txn = build_fiat_txn(
                fraud_source, mule["identity_hash"], amount, ts,
                transfer_type="ach",
                transfer_network="domestic",
                is_fraud=True,
                fraud_type="mule_network",
                fraud_network_id=network_id,
            )
            mule["balance"] += amount * 0.90
            total_aggregated += amount * 0.90
            txns.append(txn)

        # Stage 2: Each mule → aggregator (1–6 hours later)
        for mule in mules:
            if mule["identity_hash"] == aggregator["identity_hash"]:
                continue
            send_amount = mule["balance"] * 0.90
            ts = base_ts + timedelta(hours=random.uniform(1, 6))
            txn = build_fiat_txn(
                mule, aggregator["identity_hash"], send_amount, ts,
                transfer_type="wire",
                transfer_network="domestic",
                is_fraud=True,
                fraud_type="mule_network",
                fraud_network_id=network_id,
            )
            txns.append(txn)

        # Stage 3: Aggregator cashout (optionally becomes crypto bridge)
        cashout_ts = base_ts + timedelta(hours=random.uniform(6, 18))
        bridge_id  = str(uuid.uuid4())
        cashout = build_fiat_txn(
            aggregator, identity_hash(fake.email()), total_aggregated, cashout_ts,
            transfer_type="wire",
            transfer_network="international",
            is_fraud=True,
            fraud_type="laundering_fiat_leg",
            fraud_network_id=network_id,
            cross_modality_fraud_id=bridge_id,
        )
        txns.append(cashout)

        self.cross_modal_bridges.append({
            "bridge_id":    bridge_id,
            "user_hash":    aggregator["identity_hash"],
            "amount":       total_aggregated,
            "ts":           cashout_ts,
            "pattern":      "immediate_laundering",
            "network_id":   network_id,
        })

        return txns

    # ── Fraud Pattern 3: Synthetic Identity ──────────

    def _inject_synthetic_identity(self, day: int) -> list[dict]:
        """
        New account builds trust with small legit txns for 30 days,
        then receives large transfer and immediately drains.
        """
        synth = {
            "identity_hash":      identity_hash(fake.email()),
            "archetype":          "salary_worker",
            "account_age_days":   random.randint(30, 89),   # < 90 days
            "kyc_status":         "pending",
            "income_monthly":     3000,
            "velocity_baseline":  1.0,
            "balance":            random.uniform(200, 800),   # small history
            "counterparties":     [identity_hash(fake.email()) for _ in range(3)],
            "device_hash":        device_hash(fake.uuid4()),
            "ip_hash":            ip_hash(fake.ipv4()),
            "_txn_count_30d":     random.randint(5, 15),
            "_amount_sum_30d":    random.uniform(500, 2000),
            "_txn_history":       [],
        }

        txns = []
        # Receive large transfer from compromised business
        inbound_amount = random.uniform(10000, 50000)
        inbound_ts     = rand_ts(day)
        # The compromised business is the sender; we only create the receiver-side record
        receive_txn = build_fiat_txn(
            synth, identity_hash(fake.email()), 1.0,  # dummy send to self for record
            inbound_ts,
            is_fraud=True,
            fraud_type="synthetic_identity",
        )
        synth["balance"] += inbound_amount
        txns.append(receive_txn)

        # Immediately drain (100% balance out)
        drain_ts = inbound_ts + timedelta(hours=random.uniform(0.5, 4))
        drain_txn = build_fiat_txn(
            synth, identity_hash(fake.email()), synth["balance"], drain_ts,
            transfer_type="wire",
            transfer_network="international",
            is_fraud=True,
            fraud_type="synthetic_identity",
        )
        txns.append(drain_txn)
        return txns

    # ── Fraud Pattern 4: BEC ──────────────────────────

    def _inject_bec(self, legitimate_business: dict, day: int) -> list[dict]:
        """
        Attacker redirects a large legitimate invoice payment
        to a newly opened mule account.
        """
        mule_hash  = identity_hash(fake.email())
        amount     = random.uniform(10000, 500000)  # invoice-scale
        ts         = rand_ts(day)

        txn = build_fiat_txn(
            legitimate_business, mule_hash, amount, ts,
            transfer_type="wire",
            transfer_network="domestic",
            is_fraud=True,
            fraud_type="bec",
        )
        return [txn]

    # ── Structuring + Crypto (cross-modal pattern 3) ──

    def _inject_structuring(self, user: dict, day: int) -> list[dict]:
        """
        5 small withdrawals over 5 days (each < $10K threshold),
        aggregated total then bought as crypto on Day 6.
        """
        bridge_id = str(uuid.uuid4())
        total     = 0.0
        txns      = []
        amounts   = [random.uniform(2500, 9500) for _ in range(5)]

        for i, amount in enumerate(amounts):
            ts = rand_ts(max(0, day - 5 + i))
            txn = build_fiat_txn(
                user, identity_hash(fake.email()), amount, ts,
                transfer_type="ach",
                is_fraud=True,
                fraud_type="structuring",
                cross_modality_fraud_id=bridge_id,
            )
            txns.append(txn)
            total += amount

        # Register bridge for crypto leg on day 6
        bridge_ts = rand_ts(day)
        self.cross_modal_bridges.append({
            "bridge_id": bridge_id,
            "user_hash": user["identity_hash"],
            "amount":    total,
            "ts":        bridge_ts,
            "pattern":   "structuring_to_crypto",
        })
        return txns

    # ── Reverse flow setup (crypto → fiat) ───────────

    def _inject_reverse_cashout(self, user: dict, day: int) -> list[dict]:
        """
        Illicit crypto was sold; now large wire withdrawal from fiat account.
        The crypto leg is registered as a *preceding* bridge.
        """
        bridge_id = str(uuid.uuid4())
        amount    = random.uniform(50000, 200000)
        ts        = rand_ts(day)

        txn = build_fiat_txn(
            user, identity_hash(fake.email()), amount, ts,
            transfer_type="wire",
            transfer_network="international",
            is_fraud=True,
            fraud_type="laundering_fiat_leg",
            cross_modality_fraud_id=bridge_id,
        )
        # The crypto sell happened BEFORE this — CryptoEx simulator reads this bridge
        self.cross_modal_bridges.append({
            "bridge_id": bridge_id,
            "user_hash": user["identity_hash"],
            "amount":    amount * 1.02,   # crypto amount slightly higher (fees)
            "ts":        ts - timedelta(hours=random.uniform(6, 48)),
            "pattern":   "crypto_to_fiat",
        })
        return [txn]

    # ── Main run ──────────────────────────────────────

    def run(self) -> list[dict]:
        # NeoBank has 98% of identities
        active = random.sample(self.identities, int(len(self.identities) * 0.98))
        businesses = [u for u in active if u["archetype"] == "small_business"]

        # Micro-anomaly users (5% get one anomalous-but-legitimate txn)
        anomaly_users = set(random.sample(range(len(active)), int(len(active) * 0.05)))

        # Fraud injection counters
        fraud_budget = {
            "account_takeover":    int(TARGET_FIAT_TXN * FIAT_FRAUD_RATE * 0.40),
            "mule_network":        int(TARGET_FIAT_TXN * FIAT_FRAUD_RATE * 0.30),
            "synthetic_identity":  int(TARGET_FIAT_TXN * FIAT_FRAUD_RATE * 0.15),
            "bec":                 int(TARGET_FIAT_TXN * FIAT_FRAUD_RATE * 0.15),
        }
        fraud_injected = defaultdict(int)
        cross_modal_targets = int(TARGET_FIAT_TXN * FIAT_FRAUD_RATE * CROSS_MODAL_RATE)
        structuring_injected = 0
        reverse_injected = 0

        print(f"\nRunning NeoBank simulator ({SIM_DAYS} days, {len(active):,} users)...")
        for day in tqdm(range(SIM_DAYS)):
            for idx, user in enumerate(active):
                arch_cfg = ARCHETYPES[user["archetype"]]
                is_weekday = (START_TIME + timedelta(days=day)).weekday() < 5
                rate = arch_cfg["txn_per_day"] if is_weekday else arch_cfg["txn_per_day"] * 0.4
                n_txns = int(rng.poisson(rate))

                for _ in range(n_txns):
                    self.transactions.append(self._normal_txn(user, day))

                # Micro-anomaly (once per eligible user, not every day)
                if idx in anomaly_users and day == 15:
                    self.transactions.append(self._micro_anomaly(user, day))

            # Inject fraud proportionally per day
            daily_ato = fraud_budget["account_takeover"] // SIM_DAYS
            daily_mule = fraud_budget["mule_network"] // SIM_DAYS

            # ATO
            for _ in range(daily_ato):
                if fraud_injected["account_takeover"] < fraud_budget["account_takeover"]:
                    victim = random.choice(active)
                    self.transactions.extend(self._inject_ato(victim, day))
                    fraud_injected["account_takeover"] += 1

            # Mule networks
            for _ in range(max(1, daily_mule // 8)):
                if fraud_injected["mule_network"] < fraud_budget["mule_network"]:
                    pool = random.sample(active, min(15, len(active)))
                    self.transactions.extend(self._inject_mule_network(pool, day))
                    fraud_injected["mule_network"] += 8

            # Synthetic identity (2 per day)
            for _ in range(2):
                if fraud_injected["synthetic_identity"] < fraud_budget["synthetic_identity"]:
                    self.transactions.extend(self._inject_synthetic_identity(day))
                    fraud_injected["synthetic_identity"] += 2

            # BEC (1 per day if businesses available)
            if businesses and fraud_injected["bec"] < fraud_budget["bec"]:
                biz = random.choice(businesses)
                self.transactions.extend(self._inject_bec(biz, day))
                fraud_injected["bec"] += 1

            # Structuring (1 per day, 15 total)
            if structuring_injected < 15:
                user = random.choice(active)
                self.transactions.extend(self._inject_structuring(user, day))
                structuring_injected += 1

            # Reverse flow (1 every 3 days)
            if day % 3 == 0 and reverse_injected < 10:
                user = random.choice(active)
                self.transactions.extend(self._inject_reverse_cashout(user, day))
                reverse_injected += 1

        return self.transactions


# ─────────────────────────────────────────────
# CRYPTOEX SIMULATOR  (crypto-only)
# ─────────────────────────────────────────────

class CryptoExSimulator:
    def __init__(self, identities: list[dict], bridges: list[dict]):
        self.identities   = identities
        self.bridges      = bridges
        self.transactions: list[dict] = []

    # ── Normal crypto txn ─────────────────────────────

    def _normal_txn(self, user: dict, day: int) -> dict:
        arch = CRYPTO_ARCHETYPES[user.get("crypto_archetype", "hodler")]
        lo, hi = arch["amount_range"]
        amount = random.uniform(lo, hi)
        ts = rand_ts(day)

        sender_wallet   = sha256(user["crypto_wallet"] + "sender")
        receiver_wallet = sha256(fake_wallet())

        return build_crypto_txn(
            user, sender_wallet, receiver_wallet, amount, ts,
            transfer_type=random.choice(["withdrawal", "deposit", "transfer"]),
            receiver_wallet_type=random.choices(
                ["user_wallet", "exchange", "defi_contract"],
                weights=[0.60, 0.30, 0.10]
            )[0],
        )

    # ── Crypto Fraud 1: Mixer Usage ───────────────────

    def _inject_mixer(self, user: dict, day: int) -> list[dict]:
        amount    = random.uniform(10000, 500000)
        ts        = rand_ts(day)
        network_id = f"mixer_{uuid.uuid4().hex[:8]}"
        mixer_addr = sha256(random.choice(MIXER_ADDRESSES))

        # Source → Mixer
        send_to_mixer = build_crypto_txn(
            user,
            sha256(user["crypto_wallet"]),
            mixer_addr,
            amount, ts,
            transfer_type="withdrawal",
            receiver_wallet_type="mixer",
            known_mixer_interaction=True,
            receiver_wallet_age_days=9999,
            is_fraud=True,
            fraud_type="mixer_usage",
            fraud_network_id=network_id,
        )

        # Mixer → Fresh wallet (hours later)
        fresh_wallet = sha256(fake_wallet())
        ts2 = ts + timedelta(hours=random.uniform(2, 48))
        receive_from_mixer = build_crypto_txn(
            user,
            mixer_addr,
            fresh_wallet,
            amount * random.uniform(0.95, 1.0),
            ts2,
            transfer_type="deposit",
            receiver_wallet_type="user_wallet",
            known_mixer_interaction=True,
            receiver_wallet_age_days=0,
            is_fraud=True,
            fraud_type="mixer_usage",
            fraud_network_id=network_id,
        )
        return [send_to_mixer, receive_from_mixer]

    # ── Crypto Fraud 2: Rug Pull ──────────────────────

    def _inject_rug_pull(self, day: int) -> list[dict]:
        """Many victims → fake contract → dev wallet drains all."""
        network_id   = f"rugpull_{uuid.uuid4().hex[:8]}"
        contract     = sha256(fake_wallet())
        dev_wallet   = sha256(fake_wallet())
        n_victims    = random.randint(10, 50)
        pool_total   = 0.0
        txns         = []

        # Collection phase: victims buy fake tokens
        for _ in range(n_victims):
            victim_wallet = sha256(fake_wallet())
            victim_amount = random.uniform(100, 10000)
            pool_total   += victim_amount
            ts = rand_ts(day - random.randint(0, 14))   # over past 2 weeks
            fake_user = {
                "identity_hash": identity_hash(fake.email()),
                "crypto_wallet": fake_wallet(),
                "crypto_archetype": "hodler",
                "account_age_days": random.randint(100, 1000),
                "device_hash": device_hash(fake.uuid4()),
                "ip_hash": ip_hash(fake.ipv4()),
                "_txn_count_30d": random.randint(1, 20),
                "_amount_sum_30d": random.uniform(500, 10000),
            }
            txns.append(build_crypto_txn(
                fake_user, victim_wallet, contract, victim_amount, ts,
                receiver_wallet_type="contract",
                receiver_wallet_age_days=random.randint(1, 30),
                is_fraud=True,
                fraud_type="rug_pull",
                fraud_network_id=network_id,
            ))

        # Rug event: contract drains to dev wallet
        dev_user = {
            "identity_hash": identity_hash(fake.email()),
            "crypto_wallet": dev_wallet,
            "crypto_archetype": "trader",
            "account_age_days": random.randint(30, 365),
            "device_hash": device_hash(fake.uuid4()),
            "ip_hash": ip_hash(fake.ipv4()),
            "_txn_count_30d": 0, "_amount_sum_30d": 0,
        }
        rug_ts = rand_ts(day)
        txns.append(build_crypto_txn(
            dev_user, contract, dev_wallet, pool_total, rug_ts,
            transfer_type="withdrawal",
            receiver_wallet_type="user_wallet",
            receiver_wallet_age_days=0,
            is_fraud=True,
            fraud_type="rug_pull",
            fraud_network_id=network_id,
        ))
        return txns

    # ── Crypto Fraud 3: Phishing / Approval Exploit ───

    def _inject_phishing(self, user: dict, day: int) -> list[dict]:
        """Victim approves malicious contract → wallet drained instantly."""
        network_id    = f"phish_{uuid.uuid4().hex[:8]}"
        malicious_contract = sha256(fake_wallet())
        attacker_wallet    = sha256(fake_wallet())
        drain_amount  = user.get("balance", random.uniform(1000, 100000))
        ts            = rand_ts(day)

        # Approval (victim signs)
        approval = build_crypto_txn(
            user, sha256(user["crypto_wallet"]), malicious_contract,
            0.0,  # approval costs only gas
            ts,
            transfer_type="contract_approval",
            receiver_wallet_type="contract",
            receiver_wallet_age_days=random.randint(1, 14),
            is_fraud=True,
            fraud_type="phishing",
            fraud_network_id=network_id,
        )

        # Drain (seconds later)
        drain = build_crypto_txn(
            user, malicious_contract, attacker_wallet,
            drain_amount,
            ts + timedelta(seconds=random.randint(10, 120)),
            transfer_type="withdrawal",
            receiver_wallet_type="user_wallet",
            receiver_wallet_age_days=0,
            is_fraud=True,
            fraud_type="phishing",
            fraud_network_id=network_id,
        )
        drain["immediate_withdrawal"] = True
        return [approval, drain]

    # ── Crypto Fraud 4: Pig Butchering ────────────────

    def _inject_pig_butchering(self, day: int) -> list[dict]:
        """Many victims send escalating amounts to one scammer over weeks."""
        network_id    = f"pig_{uuid.uuid4().hex[:8]}"
        scammer_wallet = sha256(fake_wallet())
        n_victims     = random.randint(10, 40)
        txns          = []

        scammer_user = {
            "identity_hash": identity_hash(fake.email()),
            "crypto_wallet": scammer_wallet,
            "crypto_archetype": "trader",
            "account_age_days": random.randint(30, 180),
            "device_hash": device_hash(fake.uuid4()),
            "ip_hash": ip_hash(fake.ipv4()),
            "_txn_count_30d": 0, "_amount_sum_30d": 0,
        }

        for v in range(n_victims):
            victim_wallet = sha256(fake_wallet())
            victim_user = {
                "identity_hash": identity_hash(fake.email()),
                "crypto_wallet": victim_wallet,
                "crypto_archetype": "hodler",
                "account_age_days": random.randint(100, 2000),
                "device_hash": device_hash(fake.uuid4()),
                "ip_hash": ip_hash(fake.ipv4()),
                "_txn_count_30d": 0, "_amount_sum_30d": 0,
            }
            # Escalating payments over time
            n_payments = random.randint(3, 8)
            base_amount = random.uniform(500, 2000)
            for p in range(n_payments):
                payment_ts = rand_ts(max(0, day - random.randint(0, 30)))
                amount = base_amount * (1.3 ** p)   # escalating
                txns.append(build_crypto_txn(
                    victim_user, sha256(victim_user["crypto_wallet"]),
                    scammer_wallet, amount, payment_ts,
                    receiver_wallet_type="user_wallet",
                    is_fraud=True,
                    fraud_type="pig_butchering",
                    fraud_network_id=network_id,
                ))

        # Scammer cashes out to mixer after collecting
        total = sum(t["amount_usd"] for t in txns)
        cashout_ts = rand_ts(day)
        txns.extend(self._inject_mixer(scammer_user, day))
        return txns

    # ── Cross-modal bridge processing ─────────────────

    def _process_bridges(self):
        """Convert NeoBank cross-modal bridges into crypto legs."""
        for bridge in self.bridges:
            pattern   = bridge["pattern"]
            user_hash = bridge["user_hash"]
            amount    = bridge["amount"]
            fiat_ts   = bridge["ts"]

            # Find matching identity or create placeholder
            user = next((u for u in self.identities if u["identity_hash"] == user_hash), None)
            if user is None:
                user = {
                    "identity_hash": user_hash,
                    "crypto_wallet": fake_wallet(),
                    "crypto_archetype": "trader",
                    "account_age_days": random.randint(1, 30),
                    "device_hash": device_hash(fake.uuid4()),
                    "ip_hash": ip_hash(fake.ipv4()),
                    "_txn_count_30d": 0, "_amount_sum_30d": 0,
                }

            sender_w  = sha256(user["crypto_wallet"])
            fresh_w   = sha256(fake_wallet())

            if pattern == "immediate_laundering":
                crypto_ts = fiat_ts + timedelta(minutes=random.randint(10, 60))
                delay_label = "immediate_laundering"
            elif pattern == "delayed_laundering":
                crypto_ts = fiat_ts + timedelta(hours=random.uniform(24, 72))
                delay_label = "delayed_laundering"
            elif pattern == "structuring_to_crypto":
                crypto_ts = fiat_ts + timedelta(hours=random.uniform(1, 12))
                delay_label = "structuring_to_crypto"
            else:  # crypto_to_fiat  — crypto leg PRECEDES fiat
                crypto_ts = fiat_ts  # already shifted backward in NeoBank
                delay_label = "crypto_to_fiat"

            crypto_txn = build_crypto_txn(
                user, sender_w, fresh_w,
                amount * random.uniform(0.95, 0.99),
                crypto_ts,
                transfer_type="withdrawal",
                receiver_wallet_type="user_wallet",
                receiver_wallet_age_days=0,
                is_fraud=True,
                fraud_type="laundering_crypto_leg",
                fraud_network_id=bridge.get("network_id"),
                cross_modality_fraud_id=bridge["bridge_id"],
            )
            crypto_txn["cross_modality_pattern"] = delay_label
            crypto_txn["immediate_withdrawal"]   = True
            self.transactions.append(crypto_txn)

    # ── Main run ──────────────────────────────────────

    def run(self) -> list[dict]:
        # 35% of identities also use crypto
        active = [u for u in self.identities if u.get("has_crypto", False)]
        if not active:
            active = random.sample(self.identities, int(len(self.identities) * 0.35))

        print(f"\nRunning CryptoEx simulator ({len(active):,} users, {SIM_DAYS} days)...")

        # Fraud budgets — scaled to actual user count so rates hold at any scale
        estimated_normal_txns = len(active) * SIM_DAYS * 0.5  # avg 0.5 txns/user/day
        total_fraud_txn_budget = int(estimated_normal_txns * CRYPTO_FRAUD_RATE / (1 - CRYPTO_FRAUD_RATE))
        mixer_budget    = int(total_fraud_txn_budget * 0.35)
        rug_budget      = int(total_fraud_txn_budget * 0.25)
        phish_budget    = int(total_fraud_txn_budget * 0.20)
        pig_budget      = int(total_fraud_txn_budget * 0.20)

        mixer_count, rug_count, phish_count, pig_count = 0, 0, 0, 0

        for day in tqdm(range(SIM_DAYS)):
            for user in active:
                arch = CRYPTO_ARCHETYPES[user.get("crypto_archetype", "hodler")]
                if random.random() < arch["txn_per_day"]:
                    self.transactions.append(self._normal_txn(user, day))

            # Inject crypto fraud daily quotas
            daily = SIM_DAYS

            if mixer_count < mixer_budget:
                u = random.choice(active)
                self.transactions.extend(self._inject_mixer(u, day))
                mixer_count += 2  # 2 txns per mixer event

            if rug_count < rug_budget and day % 3 == 0:
                self.transactions.extend(self._inject_rug_pull(day))
                rug_count += 30  # ~30 txns per rug pull

            if phish_count < phish_budget:
                u = random.choice(active)
                self.transactions.extend(self._inject_phishing(u, day))
                phish_count += 2

            if pig_count < pig_budget and day % 5 == 0:
                self.transactions.extend(self._inject_pig_butchering(day))
                pig_count += 50  # many txns per pig butchering ring

        # Attach crypto legs to all fiat bridges
        print("  → Processing cross-modal bridges...")
        self._process_bridges()

        return self.transactions


# ─────────────────────────────────────────────
# FINBRIDGE SIMULATOR  (hybrid gateway)
# ─────────────────────────────────────────────

class FinBridgeSimulator:
    def __init__(self, identities: list[dict]):
        self.identities   = identities
        self.transactions: list[dict] = []

    def run(self) -> list[dict]:
        # 15% of identities use FinBridge
        active = random.sample(self.identities, int(len(self.identities) * 0.15))

        print(f"\nRunning FinBridge simulator ({len(active):,} users)...")
        for user in tqdm(active):
            n_events = random.randint(1, 5)
            for _ in range(n_events):
                amount   = sample_amount(user["archetype"])
                day      = random.randint(0, SIM_DAYS - 1)
                ts       = rand_ts(day)
                tx_link  = uuid.uuid4().hex[:8]
                is_fraud = random.random() < (FIAT_FRAUD_RATE * 1.5)   # higher risk on-ramp
                fraud_type = "laundering_fiat_leg" if is_fraud else None
                bridge_id  = str(uuid.uuid4()) if is_fraud else None

                # Record 1: Fiat leg
                fiat_rec = build_fiat_txn(
                    user,
                    sha256("finbridge_internal"),
                    amount, ts,
                    transfer_type="bank_deposit",
                    transfer_network="domestic",
                    is_fraud=is_fraud,
                    fraud_type=fraud_type,
                    cross_modality_fraud_id=bridge_id,
                )
                fiat_rec["transaction_id"] = f"finbridge_f_{tx_link}"
                fiat_rec["client_id"]      = "finbridge_prod"
                self.transactions.append(fiat_rec)

                # Record 2: Crypto leg (30 seconds later)
                sender_w   = sha256(user["crypto_wallet"])
                receiver_w = sha256(fake_wallet())
                crypto_rec = build_crypto_txn(
                    user, sender_w, receiver_w,
                    amount * 0.99, ts + timedelta(seconds=30),
                    transfer_type="crypto_purchase",
                    receiver_wallet_type="user_wallet",
                    is_fraud=is_fraud,
                    fraud_type="laundering_crypto_leg" if is_fraud else None,
                    cross_modality_fraud_id=bridge_id,
                )
                crypto_rec["transaction_id"]         = f"finbridge_c_{tx_link}"
                crypto_rec["client_id"]               = "finbridge_prod"
                crypto_rec["linked_fiat_transaction"] = fiat_rec["transaction_id"]
                self.transactions.append(crypto_rec)

        return self.transactions


# ─────────────────────────────────────────────
# VALIDATION & SUMMARY
# ─────────────────────────────────────────────

def validate_and_summarize(df: pd.DataFrame):
    print("\n" + "="*60)
    print("SIMULATION SUMMARY")
    print("="*60)

    total = len(df)
    fraud = df["is_fraud"].sum()
    print(f"Total transactions:  {total:>12,}")
    print(f"Fraud transactions:  {fraud:>12,}  ({fraud/total*100:.2f}%)")
    print(f"Legit transactions:  {total-fraud:>12,}  ({(total-fraud)/total*100:.2f}%)")

    print("\n── By client ──────────────────────────────")
    for client, grp in df.groupby("client_id"):
        f = grp["is_fraud"].sum()
        print(f"  {client:<20} {len(grp):>8,} txns  |  fraud: {f:>6,} ({f/len(grp)*100:.1f}%)")

    print("\n── By modality ────────────────────────────")
    for mod, grp in df.groupby("modality"):
        f = grp["is_fraud"].sum()
        print(f"  {mod:<10} {len(grp):>8,} txns  |  fraud: {f:>6,} ({f/len(grp)*100:.1f}%)")

    print("\n── Fraud types ────────────────────────────")
    fraud_df = df[df["is_fraud"]]
    if len(fraud_df) > 0:
        type_counts = fraud_df["fraud_type"].value_counts()
        for ft, cnt in type_counts.items():
            print(f"  {str(ft):<35} {cnt:>6,}")

    print("\n── Cross-modal fraud ──────────────────────")
    cross = df[df["cross_modality_fraud_id"].notna()]
    print(f"  Cross-modal transactions: {len(cross):,}")
    print(f"  Unique fraud sequences:   {cross['cross_modality_fraud_id'].nunique():,}")

    print("\n── Amount distribution (fiat) ─────────────")
    fiat = df[df["modality"] == "fiat"]["amount_usd"]
    if len(fiat) > 0:
        print(f"  Median:  ${fiat.median():>12,.2f}")
        print(f"  Mean:    ${fiat.mean():>12,.2f}")
        print(f"  P95:     ${fiat.quantile(0.95):>12,.2f}")
        print(f"  Max:     ${fiat.max():>12,.2f}")

    # Check shared identity_hash appears across multiple modalities
    cross_check = df.groupby("identity_hash")["modality"].nunique()
    multi_modal = (cross_check > 1).sum()
    print(f"\n── Identity cross-client check ────────────")
    print(f"  Identities in 2+ modalities: {multi_modal:,}")

    # Verify fraud rate targets
    print("\n── Fraud rate check ───────────────────────")
    fiat_df   = df[df["modality"] == "fiat"]
    crypto_df = df[df["modality"] == "crypto"]
    if len(fiat_df)   > 0: print(f"  Fiat fraud rate:   {fiat_df['is_fraud'].mean()*100:.2f}%  (target: {FIAT_FRAUD_RATE*100:.1f}%)")
    if len(crypto_df) > 0: print(f"  Crypto fraud rate: {crypto_df['is_fraud'].mean()*100:.2f}%  (target: {CRYPTO_FRAUD_RATE*100:.1f}%)")

    print("="*60)


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

if __name__ == "__main__":
    print("="*60)
    print("SENTINEL TRAINING DATA SIMULATOR  v2.0")
    print("="*60)

    # 1. Build shared identity pool
    identities = build_identity_pool(N_IDENTITIES)

    # 2. Run NeoBank (fiat) — also populates cross_modal_bridges
    neobank  = NeoBankSimulator(identities)
    fiat_txns = neobank.run()
    print(f"  → NeoBank generated {len(fiat_txns):,} transactions")
    print(f"  → Cross-modal bridges created: {len(neobank.cross_modal_bridges):,}")

    # 3. Run FinBridge (hybrid)
    finbridge = FinBridgeSimulator(identities)
    bridge_txns = finbridge.run()
    print(f"  → FinBridge generated {len(bridge_txns):,} transactions")

    # 4. Run CryptoEx (crypto) — consumes bridges from NeoBank
    cryptoex = CryptoExSimulator(identities, neobank.cross_modal_bridges)
    crypto_txns = cryptoex.run()
    print(f"  → CryptoEx generated {len(crypto_txns):,} transactions")

    # 5. Assemble and sort
    all_txns = fiat_txns + bridge_txns + crypto_txns
    df = pd.DataFrame(all_txns)
    df["timestamp"] = pd.to_datetime(df["timestamp"], format="ISO8601")
    df = df.sort_values("timestamp").reset_index(drop=True)

    # 6. Validate
    validate_and_summarize(df)

    # 7. Save
    out_path = "sentinel_training_data.jsonl"
    df.to_json(out_path, orient="records", lines=True, date_format="iso")
    print(f"\nSaved → {out_path}  ({df.memory_usage(deep=True).sum() / 1e6:.1f} MB in memory)")

    # Also save a small fraud-only sample for quick inspection
    fraud_sample = df[df["is_fraud"]].head(1000)
    fraud_sample.to_json("sentinel_fraud_sample.jsonl", orient="records", lines=True)
    print(f"Saved → sentinel_fraud_sample.jsonl  (1000 fraud rows for inspection)")